### ISSUE TITLE
Can't capture the same request executed multiple times with different response.

### ISSUE THREAD

**Issue by akhabali** [SpectoLabs/hoverfly-java#147]
**The test use case**
POST create a record   ==> 201 OK a new record created with id 1
DELETE delete the record by id 1 ==> 204 OK
DELETE delete the record by id 1 ==> 404 record doesn't exist 

**Problem**
hoverfly can't capture the 2 DELETE request and so can't simulate this two HTTP requests with the same parameters and different response.

**Possible solution**
A solution maybe to maintain the captured test requests with an order and use that order to simulate the exact execution behavior.

**Comment by JohnFDavenport** [comment]
Cross-referencing a similar issue SpectoLabs/hoverfly#679

**Comment by ia3andy** [comment]
I will make a PR about that issue. The solution would be to be able to set/unset state from the test itself.

**Comment by JohnFDavenport** [comment]
A PR for this would be very welcome @ia3andy 

I shall talk to @tommysitu and @benjih about this today

**Comment by ia3andy** [comment]
@JohnFDavenport I will start it in a few days. I have some other stuff to do before.

**Comment by tommysitu** [comment]
Hi @ia3andy,  that's a great idea, is it going to be like this in pseudocode for a login scenario:
```
start hoverfly in capture mode
hoverfly set state LOGIN=false
make a GET account request
assert response status is 401
login
hoverfly set state LOGIN=true
make the same request again
assert response status is 200
```
If that's the case, I think you need to change the Capture logic to add the current states to the `requiresStates` field in the simulation file.

**Comment by ia3andy** [comment]
@tommysitu Yes that totally makes sense I think.. 

And it would as well give a way to add a kind of indexed logic to simulation by just having an index in the state incrementing between every request so you can replay the same exact simulation :)

**Comment by benjih** [comment]
I like the sound of this. I was thinking about how to implement this, and encountered a few potential issues that I thought I should point out to you @ia3andy.

My first thought was to use the `requiresState` field on a request to store the counter. This would work only if there wasn't a hashed copy of the request in the key value store, as `requiresState` is on the expanded templable request. So it may be easier to store this directly on the hashable RequestDetails rather than as part of the state.

https://hoverfly.readthedocs.io/en/latest/pages/keyconcepts/state/state.html

The next complication is making sure it works across `RequestDetails` and `RequestMatchers`.

Once this is done, a new problem will arise, which is what to do when you've made too many requests hit all the expected responses in the sequence. Do the stateful simulations stop and present an error? Do they loop around and start at the first response again? Do they repeat the last one?

I think this should be a configurable part of the simulation, possibly on the last request in a sequence. Meaning it'd be possible to use different end of sequence patterns  within the same simulation.

If you have any questions, please feel free to ask @ia3andy, I'm always happy to help.

**Comment by ia3andy** [comment]
@benjih I think we should explode this issue in 3:

- One to be able to set/update the state from the HoverflyClient
- As @tommysitu said, one to be able to change the Capture logic to add the current states to the requiresStates field in the simulation file. 
- And the last one to have an "in sequence" simulation mode using the two previous and a counter as you said @benjih  

What do you guys think?

**Comment by tommysitu** [comment]
Sounds good to me. Yes, steps 2 and 3 requires changes in the main repo.

**Comment by tommysitu** [comment]
We are about to release v0.11.0. In this new release, you should be able to capture requests sequentially even they are identical. You just need to set config to enable stateful capture: 

```
localConfigs().enableStatefulCapture()
```
