### ISSUE TITLE
System properties not restored on Hoverfly shutdown

### ISSUE THREAD

**Issue by tommysitu** [SpectoLabs/hoverfly-java#70]
Hoverfly-java modifies the default JVM proxy host and port system properties. These values do not get reset when hoverfly shut down. If another test relies on the default values, this modification could cause test failure.

**Comment by bartoszmajsak** [comment]
It might have more subtle implications, e.g. I have tests talking with remote webdriver. Since all the traffic after hoverfly tests are routed through system proxy I obviously get errors as proxy is still there, but hoverfly process is all gone by then :)

If you haven't started working on this issue yet I'm happy to provide PR.

**Comment by tommysitu** [comment]
That's fantastic! @bartoszmajsak
